### PR TITLE
fix MovieDetails: don't show spine cover, persist dvd theme

### LINKED ISSUE #1280: *Bug* Movie page layout gets messed up when adding cover images on desktop
**Describe the bug**
On the movie details page the layout gets broken after adding a spine image as well as the covers.
The results are that the two cover images don't align with each other when hovering over them to display and the description text is showing over the graphic elements.
When adding a studio the logo takes a lot of real estate up at the top and pushes everything down the screen.

 - OS: Windows 10
 - Browser: Chrome / Edge Chromium
Did not test on mobile

A simple fix might be to not show the spine image at all on this page as it's only relevant for the 3D cover view, talking of which,  it would be great to have the 3d view embedded on the main page as an option rather than in a separate screen, like this website (though with the full box view): [https://erotik.com/en/magma-film/immergeile-muttis]
At the very least having the 3D mode remember the box colour you selected rather than reset to black on exit would be helpful.

### PR DESCRIPTION
**Pull request by leadwolf**
Closes #1280

### CODE REVIEW

**Comment by boi123212321** [comment]
I think the problem with removing the spine cover altogether makes it impossible to see if the movie has one (unless opening the 3d view for each and every one).

**Comment by leadwolf** [comment]
Should I restore it, but set a fixed width (percentage or otherwise) on the spine, and then `calc(100% - X)` on the front ?
Should I make a dialog to manage the images like on the actor details page ?

**Comment by boi123212321** [comment]
I think the layout just needs to be switched to a flex layout and it should work automatically

**Comment by leadwolf** [comment]
Will be replaced by https://github.com/leadwolf/porn-vault/tree/refactor/movie-3d

**Pull request closed without merging**
